version: "3"
services:
  backend:
    restart: always
    container_name: naisc-backend
    build: 
      context: ./NAISC-Backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  frontend:
    container_name: naisc-frontend
    build:
      context: ./NAISC-Frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend