version: "3"
services:
  frontend:
    container_name: naisc-frontend
    build:
      context: ./NAISC-Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  backend:
    restart: always
    container_name: naisc-backend
    build: 
      context: ./NAISC-Backend
      dockerfile: Dockerfile
    depends_on:
      - frontend
